### ISSUE TITLE
use rollup instead of webpack

### ISSUE THREAD

**Issue by reyhansofian** [kata-ai/kata-kit#31]
IMO we can use rollup instead of webpack, since it's simpler than webpack

**Comment by resir014** [comment]
Right now I only use Webpack for the website (using a stripped-down CRA setup).

However, for the rest of the packages, we could go with Rollup, since we can export tree-shakeable ES bundles with it.

We could use Formik's config as a reference: https://github.com/jaredpalmer/formik
