### ISSUE TITLE
use ThemedComponent on all component

### ISSUE THREAD

**Issue by reyhansofian** [kata-ai/kata-kit#33]
to maintain consistency on all components, we must use `ThemedComponent` as the component wrapper. below is the list of components that need to be adjusted

- [x] Button
  - [x] ButtonGroup
  - [x] FloatingButton
  - [x] SupportButton
  - [x] ToggleButton
- [x] Card
  - [x] Card
  - [x] CardGrid
  - [x] DashboardCard
- [x] Dashboard
- [x] Dropdown
  - [x] Dropdown
  - [x] DropdownItem
  - [x] DropdownMenu
  - [x] DropdownSelector
  - [x] DropdownToggle
- [x] Modal
  - [x] Modal
  - [x] ModalDialog
- [x] Pagination
- [x] Split Button

**Comment by resir014** [comment]
For anyone taking this issue, the docs for `ThemedComponent` is available here: https://dev-kata-kit.surge.sh/components/theme
