### ISSUE TITLE
[modal] Improve modal/drawer accessibility

### ISSUE THREAD

**Issue by resir014** [kata-ai/kata-kit#41]
A few things we can do to improve modal/drawer accessibility:

* [x] **Make modal/drawer closable by pressing the escape button.** This is crucial for easy access for people with no access to a mouse.
* [x] **Use correct ARIA roles/attributes.** References: [1](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role), [2](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html).
* [x] **Trap focus inside the modal/drawer.** This will trap the tabindex(?) focus inside the modal when we're tabbing around. [react-focus-lock](https://npmjs.com/package/react-focus-lock) seems to be the best library for this.

**Comment by resir014** [comment]
Added this issue for Hacktoberfest.

**Comment by teevik** [comment]
Hey, just recognized your name when browsing through hacktoberfest issues :P

Could i work on this?

**Comment by resir014** [comment]
Hey @teevik, sure! Feel free to ask if you got any questions.

**Comment by teevik** [comment]
> Make modal/drawer closable by pressing the escape button
Would it be good enough to add the event listener to window?
e.g
```ts
... other stuff

componentDidMount() {
  document.addEventListener('keydown', this.handleKeyDown);
}

componentWillUnmount() {
  document.removeEventListener('keydown', this.handleKeyDown);
}

handleKeyDown(event: KeyboardEvent) {
  if (this.state.show && event.key === 'Escape') {
    event.preventDefault();
    this.onCloseDrawer();
  }
}
```

Only issue with that though is it won't work to have multiple modals open at the same time, since they would all close at the same time when pressing Escape. 
But on the other side, it's bad practice to have multiple modals open at the same time, so probably wouldn't need to care about that

**Comment by resir014** [comment]
@teevik 

> Only issue with that though is it won't work to have multiple modals open at the same time, since they would all close at the same time when pressing Escape.

Yeah, this won't be a good idea. Let's skip this for now, you can go straight away to the ARIA attributes.

**Comment by teevik** [comment]
One alternative would be to force the modal to always have focus (right now it's possible to have focus on nothing), and then add react's `onKeyDown` to the modal somewhere. If i understand it correctly, that's also how react-modal does it (https://github.com/reactjs/react-modal/blob/master/src/components/ModalPortal.js#L344)

**Comment by resir014** [comment]
@teevik 	

> Hold on, i'll try it out

Awesome. Let me know how it goes.

**Comment by teevik** [comment]
@resir014 I made a prototype of one solution, but it ended up being pretty hacky. 

`react-focus-lock` is supposed to automatically set focus to the content, but seems like that only works when you have a modal that's being completely removed/added (e.g`isOpen ? <FocusLock/> : null`). 

But in our case, we have the FocusLock always exist, and disable/enable it through a prop (e.g`<FocusLock disabled={!isOpen}/>`)

So i needed to manually set the focus to the element that has the `onKeyDown` listener, and then `react-focus-lock` can take care of the rest

---

Here's the code, and the specific line https://github.com/teevik/kata-kit/commit/3f75ced4a56758fcb6a6f39a2ee8dc5c70b222aa#diff-cc23ecc802a33c17d108f01e57fd15ebR87
I put it on a quick surge.sh, to show that it's working at least http://adjoining-observation.surge.sh/components/modal

**Comment by teevik** [comment]
I feel like the preferred way is to have the `FocusLock` component handle this automatically. I'm not ready sure how to go about it though. We could create our own one, find a better library, or change an existing one

**Comment by teevik** [comment]
Actually, could i make a component for it in the `@kata-kit/common`? Would be named something like `FocusLock`, and do the same as the lib I'm using right now but actually work for our case. Then we can use the underlying libraries directly (e.g https://github.com/theKashey/focus-lock)

**Comment by resir014** [comment]
@teevik ooh, that would be a good long-term solution! Worth giving a try.

**Comment by resir014** [comment]
This issue is now complete. Thank you so much @teevik for you help!!
