### ISSUE TITLE
[Drawer] overflow bug

### ISSUE THREAD

**Issue by nurcahyopujo** [kata-ai/kata-kit#63]
**Expected Behavior**
- when drawer scrolled then drawer header should have shadow to indicate there are overflow element refer [this link](https://app.zeplin.io/project/5a9cb8011981c0e2a72fa897/screen/5aa791befef82379073a6a04)
- when drawer has overflow content, then user should able to see all of them

**Current Behavior**
- there are no shadow yet 
- bottom element is not visible because of footer

**Possible Solution**
- implement onScroll handler, when user scroll drawer to certain position then add shadow, and if scroll back to zero then remove shadow
- add more padding-bottom to Drawer body

**Steps to Reproduce**
1. Create drawer element with overflow content
2. Open drawer and scroll

**Comment by resir014** [comment]
@nurcahyopujo Found the issue. Fix is coming shortly.

I'll also add an overflow example on the storybook.
